Repository nuvlaedge/nuvlaedge, pull requests merged in 2023-07, with the labels that each got.

#103 fix: Dockerfile fix for cython 3.0.0 release on PyYaml dependency
  Dockerfile
  poetry.lock
  pyproject.toml
Labels: bug, fix

#102 feat: Validation workflow refactor
  .github/workflows/validation.yml
Labels: enhancement

#86 Add credentials to the job engine Job specification
  nuvlaedge/agent/activate.py
  nuvlaedge/agent/job.py
  nuvlaedge/agent/orchestrator/kubernetes.py
Labels: enhancement, Kubernetes

#70 fix: remove outdated TODOS and move relevant ones into issues
  nuvlaedge/agent/monitor/__init__.py
  nuvlaedge/broker/file_broker.py
  nuvlaedge/models/nuvla_resources.py
  nuvlaedge/peripherals/bluetooth/__init__.py
  nuvlaedge/peripherals/peripheral.py
  nuvlaedge/peripherals/peripheral_manager.py
  tests/agent/orchestrator/test_kubernetes_client.py
  tests/agent/test_agent.py
  tests/agent/test_nuvlaedge_common.py
  tests/agent/test_telemetry.py
Labels: fix
